### ISSUE TITLE
Builds not available for Python 3.9

### ISSUE THREAD

**Issue by ma-sadeghi** [conda-forge/edt-feedstock#9]
I wonder why `conda-forge` doesn't build `edt` for Python 3.9. Is it not yet supported? 
https://anaconda.org/conda-forge/edt/files

**Comment by william-silversmith** [comment]
This PR https://github.com/conda-forge/edt-feedstock/pull/8 mentions py39 as some kind of pending dependency? I don't know what that means.

**Comment by ma-sadeghi** [comment]
Hi @conda-forge/help-python, could you please let us know how to enforce Python 3.9 as well? Thanks!

**Comment by beckermr** [comment]
Please see the python 39 migration status on the status page. If you did not get a pr from a bot, then one or more of the dependencies of this feedstock need to be migrated to python 39 first.

**Comment by isuruf** [comment]
https://github.com/conda-forge/edt-feedstock/pull/4 was closed without merging

**Comment by william-silversmith** [comment]
Thanks for the help. Sorry for the human error. I resolved the conflicts in #4.

**Comment by ma-sadeghi** [comment]
@william-silversmith It seems that py39 builds are available (https://anaconda.org/conda-forge/edt/files), but for some reason, I can't still install `edt` on Python 3.9. I get the following error:
```
Looking for: ['edt==2.0.4']

conda-forge/noarch       [====================] (00m:01s) Done
conda-forge/linux-64     [====================] (00m:05s) Done
Encountered problems while solving.
Problem: package edt-2.0.4-py38h1fd1430_0 requires python >=3.8,<3.9.0a0, but none of the providers can be installed
```
Can you also try to reproduce? Thanks.

**Comment by isuruf** [comment]
You'll have to wait another hour or so.

**Comment by william-silversmith** [comment]
@ma-sadeghi would you mind giving it another try? I'm on an M1 and there's no arm64 build. For some reason conda isn't finding edt for me on py39 or py38.

```
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - edt

Current channels:

  - https://conda.anaconda.org/conda-forge/osx-arm64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://conda.anaconda.org/ukoethe/osx-arm64
  - https://conda.anaconda.org/ukoethe/noarch
  - https://repo.anaconda.com/pkgs/main/osx-arm64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-arm64
  - https://repo.anaconda.com/pkgs/r/noarch
```

**Comment by ma-sadeghi** [comment]
@isuruf Thanks!
@william-silversmith I just tried and sure enough, it works! Thanks for all the effort.

**Comment by william-silversmith** [comment]
Fantastic! Glad that works. Thanks @isuruf and @beckermr!!!
